name: Wheels

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: "Python version"
        default: "3.12"
        type: string
      vtk_full_version:
        description: "VTK full version"
        default: "9.4.1"
        type: string
      vtk_short_version:
        description: "VTK short version"
        default: "9.4"


jobs:

  build_wheels:
    name: Build wheel
    runs-on: ubuntu-24.04-arm  # macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        run: sudo apt update && sudo apt install -y build-essential cmake cmake-curses-gui libgl1 xvfb x11-xserver-utils libglx-mesa0 libosmesa6-dev mesa-common-dev mesa-utils freeglut3-dev ninja-build 
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Download vtk
        run: wget https://www.vtk.org/files/release/${{ github.event.inputs.vtk_short_version }}/VTK-${{ github.event.inputs.vtk_full_version }}.tar.gz

      - name: Extract vtk
        run: tar -xzf VTK-${{ github.event.inputs.vtk_full_version }}.tar.gz

      - name: Build vtk
        run: |
            cd VTK-${{ github.event.inputs.vtk_full_version }}
            ccmake -GNinja -DVTK_WHEEL_BUILD=ON -DVTK_WRAP_PYTHON=ON -DCMAKE_BUILD_TYPE=Release -DVTK_GROUP_ENABLE_Web=YES -S . -B build
            ccmake --build build

      - name: Build wheel
        run: |
            python3 -m pip install --upgrade pip setuptools wheel
            cd VTK-${{ github.event.inputs.vtk_full_version }}/build && python3 setup.py bdist_wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          path: VTK-${{ github.event.inputs.vtk_full_version }}/build/dist/*.whl
